# Generated by Django 5.1.6 on 2025-02-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
